{% set name = "anycorn" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: edb443aa46d5c396d4c53cb5f1e425b88e63d8a4fb9af2b835640a7b3351857f

build:
  noarch: python
  number: 1
  entry_points:
    - anycorn = anycorn.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - exceptiongroup >=1.2.0,<2.0
    - h11
    - h2 >=3.1.0
    - anyio >=4.0,<5.0
    - priority
    - tomli
    - typing_extensions
    - wsproto >=0.14.0
    - rich-click >=1.8.3,<2.0.0

test:
  imports:
    - anycorn
  commands:
    - pip check
    - anycorn --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/anycorn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of Hypercorn that uses AnyIO
  dev_url: https://github.com/davidbrochart/anycorn

extra:
  recipe-maintainers:
    - davidbrochart
