{% set name = "anycorn" %}
{% set version = "0.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c02d3dd7028717a24bcf915cbf2073e25a3da80cbe8d968fb5a56a97befd9e6b

build:
  noarch: python
  number: 0
  entry_points:
    - anycorn = anycorn.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python >=3.8
  run:
    - python >=3.8
    - exceptiongroup >=1.2.0,<2.0
    - h11
    - h2 >=3.1.0
    - anyio >=4.0,<5.0
    - priority
    - tomli
    - wsproto >=0.14.0

test:
  imports:
    - anycorn
  commands:
    - pip check
    - anycorn --help
  requires:
    - pip

about:
  home: https://github.com/davidbrochart/anycorn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of Hypercorn that uses AnyIO
  dev_url: https://github.com/davidbrochart/anycorn

extra:
  recipe-maintainers:
    - davidbrochart
