{% set name = "anycorn" %}
{% set version = "0.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 738056b8e2d4c773c171eeadd993e8f3d71d990c97d877cbbf7f7a689cd4e686

build:
  noarch: python
  number: 0
  entry_points:
    - anycorn = anycorn.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python >=3.8
  run:
    - python >=3.8
    - exceptiongroup >=1.2.0,<2.0
    - h11
    - h2 >=3.1.0
    - anyio >=4.0,<5.0
    - priority
    - tomli
    - typing_extensions
    - wsproto >=0.14.0

test:
  imports:
    - anycorn
  commands:
    - pip check
    - anycorn --help
  requires:
    - pip

about:
  home: https://github.com/davidbrochart/anycorn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of Hypercorn that uses AnyIO
  dev_url: https://github.com/davidbrochart/anycorn

extra:
  recipe-maintainers:
    - davidbrochart
